
// This file has been generated by the GUI designer. Do not modify.
namespace R4_Projekt
{
	public partial class UlazWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label kcalLabel;

		private global::Gtk.Label UkupnoKcalLabel;

		private global::Gtk.Button PocetnaButton;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Button buttonOdaberi;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget R4_Projekt.UlazWindow
			this.Name = "R4_Projekt.UlazWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Ulaz");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child R4_Projekt.UlazWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.WidthRequest = 400;
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.vbox4.Add(this.hbox3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.WidthRequest = 400;
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = -326;
			this.hbox4.BorderWidth = ((uint)(12));
			// Container child hbox4.Gtk.Box+BoxChild
			this.kcalLabel = new global::Gtk.Label();
			this.kcalLabel.Name = "kcalLabel";
			this.kcalLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Unesene kalorije: ");
			this.hbox4.Add(this.kcalLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.kcalLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(333));
			// Container child hbox4.Gtk.Box+BoxChild
			this.UkupnoKcalLabel = new global::Gtk.Label();
			this.UkupnoKcalLabel.Name = "UkupnoKcalLabel";
			this.UkupnoKcalLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Ukupan broj kalorija");
			this.UkupnoKcalLabel.UseUnderline = true;
			this.hbox4.Add(this.UkupnoKcalLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.UkupnoKcalLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.PocetnaButton = new global::Gtk.Button();
			this.PocetnaButton.WidthRequest = 100;
			this.PocetnaButton.HeightRequest = 50;
			this.PocetnaButton.CanFocus = true;
			this.PocetnaButton.Name = "PocetnaButton";
			this.PocetnaButton.UseUnderline = true;
			this.PocetnaButton.Label = global::Mono.Unix.Catalog.GetString("Početna");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-home", global::Gtk.IconSize.Menu);
			this.PocetnaButton.Image = w4;
			this.hbox4.Add(this.PocetnaButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.PocetnaButton]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(711));
			this.vbox4.Add(this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 0;
			this.GtkScrolledWindow.HeightRequest = 430;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.WidthRequest = 300;
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.nodeview1.Reorderable = true;
			this.nodeview1.HoverExpand = true;
			this.GtkScrolledWindow.Add(this.nodeview1);
			this.hbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w8.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonOdaberi = new global::Gtk.Button();
			this.buttonOdaberi.CanFocus = true;
			this.buttonOdaberi.Name = "buttonOdaberi";
			this.buttonOdaberi.UseUnderline = true;
			this.buttonOdaberi.Label = global::Mono.Unix.Catalog.GetString("Odaberi");
			this.vbox1.Add(this.buttonOdaberi);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonOdaberi]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox4.Add(this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1052;
			this.DefaultHeight = 568;
			this.Show();
			this.PocetnaButton.Clicked += new global::System.EventHandler(this.Pocetna);
		}
	}
}
