
// This file has been generated by the GUI designer. Do not modify.
namespace R4_Projekt
{
	public partial class DokumentacijaWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button PocetnaButton;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.TextView textview3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget R4_Projekt.DokumentacijaWindow
			this.Name = "R4_Projekt.DokumentacijaWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Dokumentacija");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child R4_Projekt.DokumentacijaWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.WidthRequest = 400;
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			this.hbox4.BorderWidth = ((uint)(9));
			// Container child hbox4.Gtk.Box+BoxChild
			this.PocetnaButton = new global::Gtk.Button();
			this.PocetnaButton.WidthRequest = 100;
			this.PocetnaButton.HeightRequest = 50;
			this.PocetnaButton.CanFocus = true;
			this.PocetnaButton.Name = "PocetnaButton";
			this.PocetnaButton.UseUnderline = true;
			this.PocetnaButton.Label = global::Mono.Unix.Catalog.GetString("Početna");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-home", global::Gtk.IconSize.Menu);
			this.PocetnaButton.Image = w1;
			this.hbox4.Add(this.PocetnaButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.PocetnaButton]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(537));
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.Buffer.Text = @"

											DOKUMENTACIJA

	Aplikacija koju izrađujemo služi za računanje unsenih kalorija tijekom dana.  Aplikacija korisniku daje podatke o 
	koje je unio u organizam kroz namirnice ili piće taj dan. Korisnik može vidjeti da li je unosom hrane zadovoljio 
	količinu	kalorija ili bi trebao smanjiti unos ili ga povećati. Korisnik također iz aplikacije može vidjeti koju količinu 
	kalorija sadrže hrana ili piće te prema tome onda odlučiti što će i koliko pojesti odnosno popiti.

	Korisnici ove aplikacije su svi ljudi koji se žele zdravo hraniti, ustanove kao na primjer bolnice, teretane, škole, vrtići,
	nutricionisti, svi kojima je bitna izrada kvalitetne prehrane.

	Buduća poboljšanja biti će da se osim energetske vrijednosti prikazuju i ostale nutritivne vrijednosti namirnica 
	(proteini, vitamini, bjelančevine, ...) te da se javlja kada je premalo odnosno previše unesenih nutritivnih vrijednosti. 	";
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.scrolledwindow2.Add(this.textview3);
			this.vbox2.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow2]));
			w5.Position = 1;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 670;
			this.DefaultHeight = 511;
			this.Show();
			this.PocetnaButton.Clicked += new global::System.EventHandler(this.Pocetna);
		}
	}
}
