
// This file has been generated by the GUI designer. Do not modify.
namespace R4_Projekt
{
	public partial class PocetnaWindow
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Image image1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.ToggleButton togglebutton1;

		private global::Gtk.Button UlazButton;

		private global::Gtk.Button DokumentacijaButton;

		private global::Gtk.Button ProfilButton;

		private global::Gtk.Button IzlazButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget R4_Projekt.PocetnaWindow
			this.Name = "R4_Projekt.PocetnaWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Početni");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(48));
			// Container child R4_Projekt.PocetnaWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = -487;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("R4_Projekt.pocetna.jpg");
			this.hbox1.Add(this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 24;
			this.vbox2.BorderWidth = ((uint)(23));
			// Container child vbox2.Gtk.Box+BoxChild
			this.togglebutton1 = new global::Gtk.ToggleButton();
			this.togglebutton1.CanDefault = true;
			this.togglebutton1.CanFocus = true;
			this.togglebutton1.Name = "togglebutton1";
			this.togglebutton1.UseUnderline = true;
			this.togglebutton1.Active = true;
			this.togglebutton1.Inconsistent = true;
			this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString("F&D ENERG-E");
			this.vbox2.Add(this.togglebutton1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.togglebutton1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UlazButton = new global::Gtk.Button();
			this.UlazButton.WidthRequest = 100;
			this.UlazButton.HeightRequest = 50;
			this.UlazButton.CanFocus = true;
			this.UlazButton.Name = "UlazButton";
			this.UlazButton.UseUnderline = true;
			this.UlazButton.Label = global::Mono.Unix.Catalog.GetString("Ulaz");
			this.vbox2.Add(this.UlazButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.UlazButton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.DokumentacijaButton = new global::Gtk.Button();
			this.DokumentacijaButton.WidthRequest = 100;
			this.DokumentacijaButton.HeightRequest = 50;
			this.DokumentacijaButton.CanFocus = true;
			this.DokumentacijaButton.Name = "DokumentacijaButton";
			this.DokumentacijaButton.UseUnderline = true;
			this.DokumentacijaButton.Label = global::Mono.Unix.Catalog.GetString("Dokumentacija");
			this.vbox2.Add(this.DokumentacijaButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.DokumentacijaButton]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.ProfilButton = new global::Gtk.Button();
			this.ProfilButton.WidthRequest = 100;
			this.ProfilButton.HeightRequest = 50;
			this.ProfilButton.CanFocus = true;
			this.ProfilButton.Name = "ProfilButton";
			this.ProfilButton.UseUnderline = true;
			this.ProfilButton.Label = global::Mono.Unix.Catalog.GetString("Profil");
			this.vbox2.Add(this.ProfilButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.ProfilButton]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.IzlazButton = new global::Gtk.Button();
			this.IzlazButton.WidthRequest = 100;
			this.IzlazButton.HeightRequest = 50;
			this.IzlazButton.CanFocus = true;
			this.IzlazButton.Name = "IzlazButton";
			this.IzlazButton.UseUnderline = true;
			this.IzlazButton.Label = global::Mono.Unix.Catalog.GetString("Izlaz");
			this.vbox2.Add(this.IzlazButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.IzlazButton]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(108));
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 737;
			this.DefaultHeight = 538;
			this.togglebutton1.HasDefault = true;
			this.Show();
			this.UlazButton.Clicked += new global::System.EventHandler(this.Ulaz);
			this.DokumentacijaButton.Clicked += new global::System.EventHandler(this.Dokumentacija);
			this.ProfilButton.Clicked += new global::System.EventHandler(this.Profil);
			this.IzlazButton.Clicked += new global::System.EventHandler(this.Izlaz);
		}
	}
}
